maintainer:
  name: Emiliano Heyns
  email: emiliano.heyns@iris-advies.com
  gpgkey: dpkg
common:
  dependencies: # apt-cache depends firefox-esr on ubuntu 20.04, except lsb-release and libgcc
    - libasound2
    - libatk1.0-0
    - libc6
    - libcairo-gobject2
    - libcairo2
    - libdbus-1-3
    - libdbus-glib-1-2
    - libfontconfig1
    - libfreetype6
    - libglib2.0-0
    - libgtk-3-0
    - libharfbuzz0b
    - libpango-1.0-0
    - libpangocairo-1.0-0
    - libstdc++6
    - libx11-6
    - libx11-xcb1
    - libxcb-shm0
    - libxcb1
    - libxcomposite1
    - libxcursor1
    - libxdamage1
    - libxext6
    - libxfixes3
    - libxi6
    - libxrandr2
    - libxrender1
    - libxtst6
    - gnupg
zotero:
  description: Zotero is a free, easy-to-use tool to help you collect, organize, cite, and share research
  dependencies:
    - libegl1|libwayland-egl1
    - libegl-mesa0
  release:
    7.0: 1
    7.0.3: 1
    7.0.11: 1
zotero6:
  description: Zotero is a free, easy-to-use tool to help you collect, organize, cite, and share research
  dependencies: []
  release:
    1.0: 1
    6.0.35: 2
zotero-beta:
  description: Zotero is a free, easy-to-use tool to help you collect, organize, cite, and share research
  dependencies:
    - libegl1|libwayland-egl1
    - libegl-mesa0
  release:
    7.0.0.65+b047f3d90: 1
    7.0.0.76+91054acfe: 1
    7.0.3.3+6f9abaaff: 1
    7.0.6.2+b4239fd4c: 2
    7.0.12.1+31bbf2acf: 1
jurism:
  description: Juris-M is a free, easy-to-use tool to help you collect, organize, cite, and share research
  dependencies:
    - default-jre
    - libreoffice-java-common
  release:
    5.0.93m18: 4
staging: staged
