#!/bin/bash

#echo "The installation of {{ client }} will have shown a message that"
#echo "  The postinst maintainerscript of the package zotero seems to use apt-key (provided by apt) without depending on gpg, gnupg, or gnupg2. This will BREAK in the future and should be fixed by the package maintainer(s)."
#echo "You can ignore this specific warning -- it is a known problem that is necessary to prevent people from being affected by https://github.com/retorquere/zotero-deb/issues/33"

APTKEY=ap
APTKEY+=t-
APTKEY+=key

if [[ -f "/etc/apt/trusted.gpg" && -f "/usr/bin/$APTKEY" && $($APTKEY --keyring /etc/apt/trusted.gpg list dpkg@iris-advies.com) ]]; then
  sudo $APTKEY --keyring /etc/apt/trusted.gpg del 1C349BCF

  if [ -x "$(command -v curl)" ]; then
    curl --silent -L https://github.com/retorquere/zotero-deb/releases/download/apt-get/deb.gpg.key | gpg --no-default-keyring --keyring gnupg-ring:/etc/apt/trusted.gpg.d/zotero.gpg --import -
    sudo chmod 644 /etc/apt/trusted.gpg.d/zotero.gpg
  elif [ -x "$(command -v wget)" ]; then
    wget -qO- https://github.com/retorquere/zotero-deb/releases/download/apt-get/deb.gpg.key | gpg --no-default-keyring --keyring gnupg-ring:/etc/apt/trusted.gpg.d/zotero.gpg --import -
    sudo chmod 644 /etc/apt/trusted.gpg.d/zotero.gpg
  fi
fi
