name: 'Manage issues and nag about debug logs'

on:
  issues:
  issue_comment:
  workflow_dispatch:

jobs:
  nag:
    runs-on: ubuntu-latest
    steps:
      - uses: retorquere/label-gun@project
        with:
          token: ${{ github.token }}
          label.awaiting: awaiting-user-feedback
          label.reopened: reopened
