name: 'Manage issues and nag about debug logs'

on:
  issues:
  issue_comment:
  workflow_dispatch:
    inputs:
      verbose:
        type: choice
        description: Log activity
        options: 
          - true
          - false

jobs:
  nag:
    runs-on: ubuntu-latest
    steps:
      - uses: retorquere/label-gun@project
        with:
          token: ${{ github.token }}
          label.awaiting: awaiting-user-feedback
          label.reopened: reopened
          verbose: '${{ github.event.inputs.verbose }}'
          assignee: retorquere
